export default  {
  ADD_NOTE: 'ADD_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',

  SET_INPUT_TITLE: 'SET_INPUT_TITLE',
  SET_INPUT_ENDDATE: 'SET_INPUT_ENDDATE',
  SET_INPUT_STATUS:'SET_INPUT_STATUS',
  SET_INPUT_PRIORITY:'SET_INPUT_PRIORITY',
  SET_INPUT_PROGRESS:'SET_INPUT_PROGRESS',
  SET_INPUT_ASSIGNERS:'SET_INPUT_ASSIGNERS',
  SET_INPUT_ID: 'SET_INPUT_ID',
  RESET_INPUT: 'RESET_INPUT',
}